name: Build Docker image and publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set version'
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        env:
            DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
            VERSION: ${{ github.event.inputs.version }}
        run: docker build -f ./Dockerfile -t $DOCKER_USER/nn-architectures-cv:latest -t $DOCKER_USER/nn-architectures-cv:$VERSION .

      - name: Push docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker push $DOCKER_USER/nn-architectures-cv:latest
          docker push $DOCKER_USER/nn-architectures-cv:$VERSION